### ISSUE TITLE
Dagger Module Composition Example

### ISSUE THREAD

**Issue by ZacSweers** [uber/crumb#23]
Have gotten a few questions about doing this, seems worth making an example.

From a high level I'm thinking basically a simple example where modules can be annotated and included in a generated module upstream, matching on some annotation. Thinking basically like CatchUp's services structure

```java
@CrumbProducer
public @interface ServiceModule {
}

@CrumbConsumer
public @interface ServiceModuleComposition {
}
```

```java
@ServiceModule
@Module
public abstract class FooModule {
  @Provides
  public String provideFooModuleString() {
    return "foo"
  }
}
```

```java
@ServiceModuleComposition
public abstract class AppModule {
  
}

// Generated
@Module(include = { FooModule.class })
public abstract class AppModuleComposition extends AppModule {

}
```

**Comment by tyvsmith** [comment]
Yeah, move forward on an example, and we'll iterate on it. Might be worth eventually creating a series of alternative artifacts based on crumb to do targeted business logic like this.

**Comment by hzsweers** [comment]
maaaaybe. Thing is it's hard to make tools that are general use since everyone's needs are different. Crumb itself was originally a json serialization helper initially after all :P

**Comment by hzsweers** [comment]
Some sketched notes I wrote up some time back for this idea in the context of catchup with scopes support. One important aspect is that I suspect this will only work if the generated module is in a separate project (think "integration project"), but will need to check. My concern is that referencing generated code in an annotation won't actually work even with rounds.

```java
@PluginPoint(
  value = Feature.class,
  modules = {...},  // Optional modules
  subcomponents = {...}  // Optional subcomponents
)
@ContributedPluginsScope // Optional scope
interface IntegrationPoint {
  // Can be abstract class too
}

@Module(
  include = { FeatureModule.class } // Can include downstream modules, useful for things with dependencies
)
abstract class IntegrationPointModule implements IntegrationPoint {
  
  // @ContributedPluginsScope
  @Multibinds
  abstract Set<Feature> features();

  @Provides
  @IntoSet
  static Feature provideFooFeature() {
    // Can include singly-annoted things, useful for simple items
    // TODO What about constructor injection? Probably modules
    return new FooFeature();
  }
}
```

**Comment by JayNewstrom** [comment]
My use case for this is very similar to the issue description. I don't need scoping/submodules. Basically I'd just annotate modules in library gradle projects, and expect them in my app gradle project. 

Is this something you'd consider accepting as a first draft of this?

**Comment by ZacSweers** [comment]
I'm going to close this for now with the above library example linked as an example. I worry that trying to build what's described above would turn into a project bigger than this actual library :)
