### ISSUE TITLE
Support Gradle Incremental Annotation Processing

### ISSUE THREAD

**Issue by JayNewstrom** [uber/crumb#33]
It would be nice if crumb would support incremental annotation processing released in Gradle 4.7.
Given that crumb uses resources, it doesn't look like that's going to work. See https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing

A [similar project](https://github.com/JayNewstrom/composite) I work on solves a similar problem (with a million times less flexibility). The library TLDR is this:
- The [composite equivalent](https://github.com/JayNewstrom/Composite/blob/master/runtime/src/main/java/com/jaynewstrom/composite/runtime/LibraryModule.java) of `CrumbProducer` generates a class with an [annotation](https://github.com/JayNewstrom/Composite/blob/master/runtime/src/main/java/com/jaynewstrom/composite/runtime/LibraryModuleIndexer.java) on it.
- The [composite equivalent](https://github.com/JayNewstrom/Composite/blob/master/runtime/src/main/java/com/jaynewstrom/composite/runtime/AppModule.java) of `CrumbConsumer` looks for the generated classes annotated by the step above

I think an approach similar to this would allow the crumb annotation processors to be incremental.

This would essentially change the implementation details within crumb to use classes (again, that can be proguarded out) instead of resources.

I'd be willing to help/do the work for this if it's a direction that the library maintainers deem appropriate.

**Comment by hzsweers** [comment]
Yep that's the one! Let's touch base again once that's available

**Comment by JayNewstrom** [comment]
Looks like this support just got merged in! https://github.com/gradle/gradle/pull/8797

**Comment by ZacSweers** [comment]
Nice. I can take a look at this sooooon-ish

**Comment by ZacSweers** [comment]
Hmm. So the resources bit works, but crumb can be a bit weird in that it should re-run if dependencies change. I think gradle will skip incremental processing in this event anyway, but will check. Alternatively, we can also add the type elements of transitive dependencies picked up too in consumers

**Comment by ZacSweers** [comment]
It's also unclear what a processor that generates no sources is supposed to do

**Comment by ZacSweers** [comment]
it seems like the resources support is really more oriented toward making emission of side-effect resources not impact incrementalism of a main source-emitting processor, not necessarily about aggregating resources. I think this makes incremental support for this project not really viable beyond maybe making producer extensions incremental-friendly. Consumers would always be non-incremental since they read resources. Does that seem worthwhile/viable?

Should note that the discussion is still ongoing in the original gradle issue. I'm trying to understand how tools that use something like a ServiceLoader wouldn't break in this paradigm or if they're just unsupported in general.

**Comment by JayNewstrom** [comment]
Yeah, the benefit is certainly not as much unless everything is incremental.

**Comment by ZacSweers** [comment]
I've been digging a bit, and there _is_ a way we can do this, but requires an overhaul of the current core API to not be resources-based. Glide makes this work by basically generating a placeholder type with an annotation containing all the relevant metadata, I guess with the expectation that it would just be removed in release by proguard or something similar. All of these types are put in the same package, so just at the final "app"-level, it loads all the types in that package and looks for any annotated with its `Index` annotation, then reads metadata from that.

Then no resources are used at all, at the cost of basically generating boilerplate code. I think this is an ok tradeoff. We can also do our best to obfuscate this class from public API (package private, comment, etc).

At a high level:
- crumb producers: similar to GlideLibraryModules. For every one, generate a holder class with an annotation of the metadata it produces
- crumb consumers: similar to GlideAppModules.
